### ISSUE TITLE
Utf8 issue on robotframework-metrics

### ISSUE THREAD

**Issue by adiralashiva8** [adiralashiva8/robotframework-metrics#48]
I encountered an utf8 issue after the generation of my test suite metrics (126 tests).

> python robotmetrics.py -email false -inputpath
"MYPATH" -output output.xml -report report.html -log l
og.html
Converting .xml to .html file. This may take few minutes...
1 of 6: Capturing dashboard content...
2 of 6: Capturing suite metrics...
3 of 6: Capturing test metrics...
4 of 6: Capturing keyword metrics...Traceback (most recent call last):
  File "robotmetrics.py", line 848, in <module>
    result.visit(KeywordResults())
  File "C:\Python27\lib\site-packages\robot\result\executionresult.py", line 118
, in visit
    visitor.visit_result(self)
  File "C:\Python27\lib\site-packages\robot\result\visitor.py", line 44, in visi
t_result
    result.suite.visit(self)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 161, in vi
sit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 86, in visit
_suite
    suite.suites.visit(self)
  File "C:\Python27\lib\site-packages\robot\model\itemlist.py", line 76, in visi
t
    item.visit(visitor)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 161, in vi
sit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 86, in visit
_suite
    suite.suites.visit(self)
  File "C:\Python27\lib\site-packages\robot\model\itemlist.py", line 76, in visi
t
    item.visit(visitor)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 161, in vi
sit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 86, in visit
_suite
    suite.suites.visit(self)
  File "C:\Python27\lib\site-packages\robot\model\itemlist.py", line 76, in visi
t
    item.visit(visitor)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 161, in vi
sit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 87, in visit
_suite
    suite.tests.visit(self)
  File "C:\Python27\lib\site-packages\robot\model\itemlist.py", line 76, in visi
t
    item.visit(visitor)
  File "C:\Python27\lib\site-packages\robot\model\testcase.py", line 74, in visi
t
    visitor.visit_test(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 108, in visi
t_test
    test.keywords.visit(self)
  File "C:\Python27\lib\site-packages\robot\model\itemlist.py", line 76, in visi
t
    item.visit(visitor)
  File "C:\Python27\lib\site-packages\robot\model\keyword.py", line 118, in visi
t
    visitor.visit_keyword(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 129, in visi
t_keyword
    if self.start_keyword(kw) is not False:
  File "robotmetrics.py", line 837, in start_keyword
    table_td.string = str(kw.kwname)

**UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 40:
 ordinal not in range(128)**

**Comment by adiralashiva8** [comment]
Suggested solution:
reload(sys)
sys.setdefaultencoding('utf8')

Drawbacks: https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by bkhouri** [comment]
you don't need to use `sys.setdefaultencoding('utf8')` to decode as you may be able to specify the decode type (e.g. `UTF-8` when reading the file).

**Comment by adiralashiva8** [comment]
@bkhouri As per your suggestion I have made this change like - https://github.com/adiralashiva8/robotframework-metrics/blob/a4c0c60bd2d2e40c1b4f33f67cb13f2d7c441436/setup.py#L4

Hope this may fix this issue! Need to test (since I could not replicate this issue)

**Comment by bkhouri** [comment]
In the example you sent, I think it's overkill since the `__version__.py`
should be a controlled file in the repository.  Why don't you just import
the module instead?

**Comment by adiralashiva8** [comment]
this issue is due to converting xml content to str() as we discussed in this thread - https://robotframework.slack.com/archives/C2U0JE1T9/p1568032459129000

I have pushed the changes to fix this issue (into master)
